### ISSUE TITLE
No code

### ISSUE THREAD

**Issue by adriendb** [thedeadrobots/pixi#4]
Upload the source code please.

**Comment by kingthorin** [comment]
Yup code would be good :zap:

**Comment by kingthorin** [comment]
Per the webcast [1], the hope is to release the full deal under the OWASP org [2].

[1] https://appsecpodcast.org/2017/09/05/hacking-apis-and-web-services-with-devslop-s02e13/
[2] https://github.com/OWASP

**Comment by shehackspurple** [comment]
Rick?  What?  Confused.

I’m going to yank the code out of the container and put it in a repo this month-ish.  I have a lot of travel, but I think I can swing it.


@SheHacksPurple
OWASP Ottawa Chapter Leader: https://www.meetup.com/OWASP-Ottawa/ 
OWASP DevSlop Project Leader: https://www.owasp.org/index.php/OWASP_DevSlop_Project
https://www.slideshare.net/TanyaJanca

**Comment by infomaven** [comment]
Was the source code migrated?  If so, a URL would be most appreciated.

**Comment by kingthorin** [comment]
@infomaven https://github.com/DevSlop/Pixi

**Comment by infomaven** [comment]
Thank you kingthorin!
